---
# tasks file for roles/nginx
- name: Install Nginx from Cyan Aptly Repository Mirror
  become: yes
  apt:
    name: "{{ packages }}"
  ignore_errors: "{{ ansible_check_mode }}"
  vars:
    packages:
      - nginx

- name: Create Openssl req.conf File
  become: yes
  copy:
    src: req.conf
    dest: /etc/nginx/req.conf

- name: Set hostname in req.conf config file
  become: yes
  shell: sed -i s/XXXXX/$(hostname)/g /etc/nginx/req.conf

- name: Set ip address in req.conf config file
  become: yes
  shell: sed -i s/YYYYY/$(hostname -i | cut -d' ' -f1)/g /etc/nginx/req.conf

- name: Create nginx default config file
  become: yes
  copy:
    src: default.nginx
    dest: /etc/nginx/sites-available/default

- name: Set hostname in nginx default config file
  become: yes
  shell: sed -i s/XXXXX/$(hostname)/g /etc/nginx/sites-available/default

- name: Set ip address in nginx default config file
  become: yes
  shell: sed -i s/YYYYY/$(hostname -i | cut -d' ' -f1)/g /etc/nginx/sites-available/default

- name: Create Nginx automation directory
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '/root/.nginx_automate'

- name: Upload nginx proxy initialization script
  become: yes
  copy:
    src: nginx_init.sh
    dest: /root/.nginx_automate/nginx_init.sh

- name: Change permissions on nginx_init.sh
  become: yes
  file:
    path: /root/.nginx_automate/nginx_init.sh
    mode: "u+rwx"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Run Nginx Initialization script
  become: yes
  command: /root/.nginx_automate/nginx_init.sh
  args:
    executable: /bin/bash
